
.travis.yml:

install:
  - npm install -g npm@2

language: node_js
node_js:
  - "0.11.x"

before_script:
  - npm install
  - mysql -u root -e 'create database travis_db;'
  - mysql -u root travis_db < tables.sql

script: mocha
